DadWebDB/DadWebDB/Models/DadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DadWebDB.Models
{
    public class DadModel
    {
        public int ID { get; set; }
        public string Like { get; set; }
        public string Why { get; set; }
    }
}

DadWebDB/DadWebDB/Models/ErrorViewModel.cs
using System;

namespace DadWebDB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DadWebDB/DadWebDB/Controllers/DadModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DadWebDB.Data;
using DadWebDB.Models;

namespace DadWebDB.Controllers
{
    public class DadModelsController : Controller
    {
        private readonly DadModelContext _context;

        public DadModelsController(DadModelContext context)
        {
            _context = context;
        }

        // GET: DadModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.Dad.ToListAsync());
        }

        // GET: DadModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dadModel = await _context.Dad
                .SingleOrDefaultAsync(m => m.ID == id);
            if (dadModel == null)
            {
                return NotFound();
            }

            return View(dadModel);
        }

        // GET: DadModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DadModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Like,Why")] DadModel dadModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dadModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dadModel);
        }

        // GET: DadModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dadModel = await _context.Dad.SingleOrDefaultAsync(m => m.ID == id);
            if (dadModel == null)
            {
                return NotFound();
            }
            return View(dadModel);
        }

        // POST: DadModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Like,Why")] DadModel dadModel)
        {
            if (id != dadModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dadModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DadModelExists(dadModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dadModel);
        }

        // GET: DadModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dadModel = await _context.Dad
                .SingleOrDefaultAsync(m => m.ID == id);
            if (dadModel == null)
            {
                return NotFound();
            }

            return View(dadModel);
        }

        // POST: DadModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dadModel = await _context.Dad.SingleOrDefaultAsync(m => m.ID == id);
            _context.Dad.Remove(dadModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DadModelExists(int id)
        {
            return _context.Dad.Any(e => e.ID == id);
        }
    }
}

DadWebDB/DadWebDB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DadWebDB.Models;

namespace DadWebDB.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult DB()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DadWebDB/DadWebDB/Views/DadModels/Create.cshtml
@model DadWebDB.Models.DadModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>DadModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Like" class="control-label"></label>
                <input asp-for="Like" class="form-control" />
                <span asp-validation-for="Like" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Why" class="control-label"></label>
                <input asp-for="Why" class="form-control" />
                <span asp-validation-for="Why" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DadWebDB/DadWebDB/Views/DadModels/Delete.cshtml
@model DadWebDB.Models.DadModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DadModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Why)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Why)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DadWebDB/DadWebDB/Views/DadModels/Details.cshtml
@model DadWebDB.Models.DadModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DadModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Why)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Why)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DadWebDB/DadWebDB/Views/DadModels/Edit.cshtml
@model DadWebDB.Models.DadModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DadModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Like" class="control-label"></label>
                <input asp-for="Like" class="form-control" />
                <span asp-validation-for="Like" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Why" class="control-label"></label>
                <input asp-for="Why" class="form-control" />
                <span asp-validation-for="Why" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DadWebDB/DadWebDB/Views/DadModels/Index.cshtml
@model IEnumerable<DadWebDB.Models.DadModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Like)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Why)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Like)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Why)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DadWebDB/DadWebDB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Dad";
}

<div id="anotherCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
    <ol class="carousel-indicators">
        <li data-target="#anotherCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#anotherCarousel" data-slide-to="1"></li>
        <li data-target="#anotherCarousel" data-slide-to="2"></li>
        <li data-target="#anotherCarousel" data-slide-to="3"></li>
        <li data-target="#anotherCarousel" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active" style="text-align:center;padding: 100px 0">
            <h1>Dad likes Cats</h1>
        </div>
        <div class="item active" style="text-align:center;padding: 100px 0">
            <h1>and Bats</h1>
        </div>
        <div class="item active" style="text-align:center;padding: 100px 0">
            <h1>and Mats</h1>
        </div>
        <div class="item active" style="text-align:center;padding: 100px 0">
            <h1>and Hats</h1>
        </div>
        <div class="item active" style="text-align:center;padding: 100px 0">
            <h1>and Eats</h1>
        </div>
    </div>
</div>

DadWebDB/DadWebDB/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Dad doesn't like being disturbed. So don't disturb him at:</h1>
<address>
    One Two Three Fourth Street<br />
    Mars<br />
    <abbr title="Phone">P:</abbr>
    555.5555.5555555-55
</address>

DadWebDB/DadWebDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active" style="text-align:center;padding:100px 0">
            <h1>Hello Dad</h1>
        </div>
        <div class="item" style="text-align:center;padding:100px 0">
            <h1>This is a website for you</h1>
        </div>
        <div class="item" style="text-align:center;padding:100px 0">
            <h1>Happy 60th Birthday</h1>
        </div>
        <div class="item" style="text-align:center;padding:100px 0">
            <h1>You Made It!</h1>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

DadWebDB/DadWebDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dad Web DB</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dad Web DB</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="DadModels" asp-action="Index">DB</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Dad Web DB</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>